### ISSUE TITLE
How would I hide the .html extension in the web address for non-index.html files?

### ISSUE THREAD

**Issue by nayasinghania** [project-mae/project-mae.github.io#2]

**Comment by dynafide** [comment]
The easiest trick to remove .html is to put each file in its own directory and name the file itself index.html so that it is the index page for that directory. For example, to get `/about` as the path, you would put the HTML file at `/about/index.html` in the repository.

**Comment by nayasinghania** [comment]
Then for an href to that page would I put href='about' or href='about/index.html'?

**Comment by dynafide** [comment]
For a reference you would put `/about` as the path.
