### ISSUE TITLE
Fix navbar covering up most content on mobile

### ISSUE THREAD

**Issue by dynafide** [project-mae/project-mae.github.io#3]
On mobile devices, the nav bar at the top covers up the majority of the screen, as pictured below:

![image](https://user-images.githubusercontent.com/74845094/116288925-9cd30300-a757-11eb-92e3-487517c3c96a.png)

This could probably be fixed by either making it static with the rest of the page, or allowing it to collapse on mobile and instead show a hamburger button.

**Comment by nayasinghania** [comment]
I will change it to a hamburger menu because I think that would look better. Thanks for pointing out this issue

**Comment by nayasinghania** [comment]
![image](https://user-images.githubusercontent.com/74111380/116486104-7219a500-a852-11eb-8083-7e9f5020851a.png)

Is this better?

**Comment by dynafide** [comment]
The font is a bit small for the size but other than that I think it looks great.

**Comment by nayasinghania** [comment]
Font size has been adjusted
